//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace DAL
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Utilisateur))]
    public partial class Administrateur
    {
        #region Primitive Properties
        [DataMember]
        public virtual int CIN
        {
            get { return _cIN; }
            set
            {
                if (_cIN != value)
                {
                    if (Utilisateur != null && Utilisateur.CIN != value)
                    {
                        Utilisateur = null;
                    }
                    _cIN = value;
                }
            }
        }
        private int _cIN;

        #endregion
        #region Navigation Properties
        
    
        [DataMember]
        public virtual Utilisateur Utilisateur
        {
            get { return _utilisateur; }
            set
            {
                if (!ReferenceEquals(_utilisateur, value))
                {
                    var previousValue = _utilisateur;
                    _utilisateur = value;
                    FixupUtilisateur(previousValue);
                }
            }
        }
        private Utilisateur _utilisateur;

        #endregion
        #region Association Fixup
    
        private void FixupUtilisateur(Utilisateur previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.Administrateur, this))
            {
                previousValue.Administrateur = null;
            }
    
            if (Utilisateur != null)
            {
                Utilisateur.Administrateur = this;
                if (CIN != Utilisateur.CIN)
                {
                    CIN = Utilisateur.CIN;
                }
            }
        }

        #endregion
    }
}
