//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace DAL
{
    public partial class ProjetEntities : ObjectContext
    {
        public const string ConnectionString = "name=ProjetEntities";
        public const string ContainerName = "ProjetEntities";
    
        #region Constructors
    
        public ProjetEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ProjetEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ProjetEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Administrateur> Administrateur
        {
            get { return _administrateur  ?? (_administrateur = CreateObjectSet<Administrateur>("Administrateur")); }
        }
        private ObjectSet<Administrateur> _administrateur;
    
        public ObjectSet<Condidat> Condidat
        {
            get { return _condidat  ?? (_condidat = CreateObjectSet<Condidat>("Condidat")); }
        }
        private ObjectSet<Condidat> _condidat;
    
        public ObjectSet<Entretien> Entretien
        {
            get { return _entretien  ?? (_entretien = CreateObjectSet<Entretien>("Entretien")); }
        }
        private ObjectSet<Entretien> _entretien;
    
        public ObjectSet<OffreEmploi> OffreEmploi
        {
            get { return _offreEmploi  ?? (_offreEmploi = CreateObjectSet<OffreEmploi>("OffreEmploi")); }
        }
        private ObjectSet<OffreEmploi> _offreEmploi;
    
        public ObjectSet<Recruteur> Recruteur
        {
            get { return _recruteur  ?? (_recruteur = CreateObjectSet<Recruteur>("Recruteur")); }
        }
        private ObjectSet<Recruteur> _recruteur;
    
        public ObjectSet<Utilisateur> Utilisateur
        {
            get { return _utilisateur  ?? (_utilisateur = CreateObjectSet<Utilisateur>("Utilisateur")); }
        }
        private ObjectSet<Utilisateur> _utilisateur;

        #endregion
    }
}
